// GAMES
export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
// render games by genre
export const FETCH_GAMES_BY_GENRE = 'FETCH_GAMES_BY_GENRE';
// GENRES
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
