// GAMES
export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
// render games by genre
export const FETCH_GAMES_BY_GENRE = 'FETCH_GAMES_BY_GENRE';
// GENRES
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
// GAME DETAIL
export const FETCH_GAME_DETAIL = 'FETCH_GAME_DEATAIL';
export const FETCH_GAME_DETAIL_SUCCESS = 'FETCH_GAME_DEATAIL_SUCCESS';
// VIDEO ACTION
export const OPEN_VIDEO = 'OPEN_VIDEO';
export const CLOSE_VIDEO = 'CLOSE_VIDEO';
// USERS

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LOGIN_USER = 'LOGIN_USER'
export const UPDATE_USER_USERNAME = 'UPDATE_USER_USERNAME'